"""add statistics

Revision ID: 035cb4490ef1
Revises: 991ecb2bf269
Create Date: 2025-06-11 14:20:07.255593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035cb4490ef1'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('avg_days', sa.Float(), nullable=False),
    sa.Column('min_days', sa.Float(), nullable=False),
    sa.Column('max_days', sa.Float(), nullable=False),
    sa.Column('job_postings_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics', schema='public')
    # ### end Alembic commands ###
